In [4]:
import numpy as np

# Load the provided npy file
file_path =  r'C:\Users\boddu\Downloads\map_soc_walls_3.npy'
data = np.load(file_path)

# Print the shape and a small sample of the data to understand its structure
data_shape = data.shape
data_sample = data[:5]  # Take a small sample for inspection

data_shape, data_sample


((764, 856),
 array([[205, 205, 205, ..., 205, 205, 205],
        [205, 205, 205, ..., 205, 205, 205],
        [205, 205, 205, ..., 205, 205, 205],
        [205, 205, 205, ..., 205, 205, 205],
        [205, 205, 205, ..., 205, 205, 205]], dtype=uint8))

In [5]:
# Replace all occurrences of 205 with 0
data[data == 205] = 0

# Save the modified array to a new .npy file
new_file_path = r'C:\Users\boddu\Downloads\map_soc_walls_3_modified.npy'
np.save(new_file_path, data)

new_file_path


'C:\\Users\\boddu\\Downloads\\map_soc_walls_3_modified.npy'

In [1]:
import numpy as np

# Load the .npy file
file_path = r'C:\Users\boddu\Downloads\map_soc_walls_3_modified.npy'
data = np.load(file_path)

# Display the data shape and a small sample before making changes
data_shape = data.shape
sample_before = data[:5]

data_shape, sample_before


((764, 856),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8))

In [3]:
# Convert all 254 to 0 and all 0 to 254
data_converted = np.where(data == 254, 0, np.where(data == 0, 254, data))

# Display a small sample after making changes
sample_after = data_converted[:5]

# Save the modified array to a new .npy file
modified_file_path = r'C:\Users\boddu\Downloads\map_soc_walls_3_modified_converted.npy'
np.save(modified_file_path, data_converted)

sample_after, modified_file_path


(array([[254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 254, 254, 254]], dtype=uint8),
 'C:\\Users\\boddu\\Downloads\\map_soc_walls_3_modified_converted.npy')